import esbuild from 'esbuild'
import process from 'process'
import sveltePlugin from 'esbuild-svelte'
import { sveltePreprocess } from 'svelte-preprocess'
import inlineWorkerPlugin from 'esbuild-plugin-inline-worker'
import fs from 'fs'
import path from 'path'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'
const pluginDir = '/Users/sunwei/Desktop/mdf-661/.obsidian/plugins/mdfriday';

// 复制项目根目录的 styles.css 到插件目录
const copyStylesCss = () => {
	const srcStylesPath = path.join(process.cwd(), 'styles.css');
	if (fs.existsSync(srcStylesPath)) {
		if (prod) {
			// 生产模式：styles.css 已经在根目录，不需要移动
			console.log('Production: styles.css is in place');
		} else {
			// 开发模式：复制到插件目录
			const destStylesPath = path.join(pluginDir, 'styles.css');
			fs.copyFileSync(srcStylesPath, destStylesPath);
			console.log(`Copied styles.css to ${destStylesPath}`);
		}
	} else {
		console.warn('Warning: styles.css not found in project root');
	}
};

// 构建完成后的回调函数，用于处理CSS文件
const onBuildComplete = (result) => {
	// 首先复制项目根目录的 styles.css（这是主要的样式文件）
	copyStylesCss();
	
	// 检查是否有 metafile 信息（处理 Svelte 等生成的 CSS）
	if (result && result.metafile) {
		// 查找所有输出的 CSS 文件
		const outputs = Object.keys(result.metafile.outputs).filter(file => file.endsWith('.css'));
		
		if (outputs.length > 0) {
			console.log(`Found CSS outputs: ${outputs.join(', ')}`);
			
			// 处理每个 CSS 文件（这些是构建过程中生成的，与 styles.css 不同）
			outputs.forEach(cssFile => {
				console.log(`Note: Build generated ${cssFile} (Svelte CSS is injected, this may be empty)`);
			});
		}
	}
};

// External modules that should not be bundled
// These are provided by Obsidian or the Electron runtime (desktop only)
const externals = [
	// Obsidian and Electron core
	'obsidian',
	'electron',
	'crypto',
	// CodeMirror (provided by Obsidian)
	'@codemirror/autocomplete',
	'@codemirror/closebrackets',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/comment',
	'@codemirror/fold',
	'@codemirror/gutter',
	'@codemirror/highlight',
	'@codemirror/history',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/matchbrackets',
	'@codemirror/panel',
	'@codemirror/rangeset',
	'@codemirror/rectangular-selection',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/stream-parser',
	'@codemirror/text',
	'@codemirror/tooltip',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	// Node.js builtins used by desktop-only features (publish/ftp/foundry)
	// These are available in Obsidian Desktop (Electron) but not on mobile
	// The code using these is only executed on desktop (guarded by Platform.isDesktop)
	'fs',
	'fs/promises',
	'path',
	'net',
	'tls',
	'stream',
	'stream/promises',
	'http',
	'https',
	'util',
	'os',
	'node:fs',
	'node:fs/promises',
	'node:path',
	'node:stream',
];

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		global: 'window',
	},
	external: externals,
	// Browser platform settings - critical for mobile support
	// This ensures esbuild uses browser versions of packages instead of Node.js versions
	platform: 'browser',
	mainFields: ['browser', 'module', 'main'],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	metafile: true, // 启用元数据输出以便追踪生成的文件
	plugins: [
		inlineWorkerPlugin({
			external: externals,
			treeShaking: true,
		}),
		sveltePlugin({
			preprocess: sveltePreprocess(),
			compilerOptions: { 
				css: 'injected',
				// Enable Svelte 4 component API compatibility for existing components
				compatibility: {
					componentApi: 4
				}
			},
		}),
	],
	outfile: prod ? 'main.js' : path.join(pluginDir, 'main.js'),
};

// 强制 CSS 提取为单独文件
buildOptions.loader = buildOptions.loader || {};
buildOptions.loader['.css'] = 'css';

if (prod) {
	esbuild
		.build(buildOptions)
		.then(onBuildComplete)
		.catch(() => process.exit(1));
} else {
	// 开发模式：首先复制 styles.css
	copyStylesCss();
	
	// 监听 styles.css 变化并复制
	const stylesPath = path.join(process.cwd(), 'styles.css');
	fs.watchFile(stylesPath, { interval: 500 }, (curr, prev) => {
		if (curr.mtime !== prev.mtime) {
			copyStylesCss();
		}
	});
	
	const context = await esbuild.context(buildOptions);
	await context.watch();
}
