import esbuild from 'esbuild'
import process from 'process'
import sveltePlugin from 'esbuild-svelte'
import { sveltePreprocess } from 'svelte-preprocess'
import inlineWorkerPlugin from 'esbuild-plugin-inline-worker'
import fs from 'fs'
import path from 'path'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'
const pluginDir = '/Users/sunwei/Desktop/mdf-661/.obsidian/plugins/mdfriday';

// 重命名 CSS 文件的函数
const renameCssFile = (cssPath, targetPath) => {
	try {
		if (fs.existsSync(cssPath)) {
			// 重命名（移动）CSS 文件
			fs.renameSync(cssPath, targetPath);
			console.log(`✓ Renamed CSS to ${targetPath}`);
			return true;
		}
	} catch (error) {
		console.error(`Failed to rename CSS file: ${error.message}`);
	}
	return false;
};

// esbuild 插件：在构建完成后重命名 main.css 为 styles.css
const cssRenamePlugin = {
	name: 'css-rename',
	setup(build) {
		build.onEnd((result) => {
			// 检查是否有 metafile 信息
			if (result && result.metafile) {
				// 查找所有输出的 CSS 文件
				const outputs = Object.keys(result.metafile.outputs).filter(file => file.endsWith('.css'));
				
				if (outputs.length > 0) {
					console.log(`Found CSS outputs: ${outputs.join(', ')}`);
					
					// 将 main.css 重命名为 styles.css（Obsidian 要求的文件名）
					outputs.forEach(cssFile => {
						const cssPath = path.resolve(cssFile);
						
						// 如果是 main.css，重命名为 styles.css
						if (cssFile.includes('main.css')) {
							const targetPath = prod 
								? path.join(process.cwd(), 'styles.css')
								: path.join(pluginDir, 'styles.css');
							
							renameCssFile(cssPath, targetPath);
						}
					});
				}
			}
		});
	}
};

// 构建完成后的回调函数（用于生产模式）
const onBuildComplete = (result) => {
	console.log('✓ Build completed successfully');
};

// External modules that should not be bundled
// These are provided by Obsidian or the Electron runtime (desktop only)
const externals = [
	// Obsidian and Electron core
	'obsidian',
	'electron',
	'crypto',
	// CodeMirror (provided by Obsidian)
	'@codemirror/autocomplete',
	'@codemirror/closebrackets',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/comment',
	'@codemirror/fold',
	'@codemirror/gutter',
	'@codemirror/highlight',
	'@codemirror/history',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/matchbrackets',
	'@codemirror/panel',
	'@codemirror/rangeset',
	'@codemirror/rectangular-selection',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/stream-parser',
	'@codemirror/text',
	'@codemirror/tooltip',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	// Node.js builtins used by desktop-only features (publish/ftp/foundry)
	// These are available in Obsidian Desktop (Electron) but not on mobile
	// The code using these is only executed on desktop (guarded by Platform.isDesktop)
	'fs',
	'fs/promises',
	'path',
	'net',
	'tls',
	'stream',
	'stream/promises',
	'http',
	'https',
	'util',
	'os',
	'process',
	'url',
	'node:fs',
	'node:fs/promises',
	'node:path',
	'node:stream',
	'node:process',
	'node:url',
];

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		global: 'window',
	},
	external: externals,
	// Browser platform settings - critical for mobile support
	// This ensures esbuild uses browser versions of packages instead of Node.js versions
	platform: 'browser',
	mainFields: ['browser', 'module', 'main'],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	metafile: true, // 启用元数据输出以便追踪生成的文件
	plugins: [
		inlineWorkerPlugin({
			external: externals,
			treeShaking: true,
		}),
		sveltePlugin({
			preprocess: sveltePreprocess(),
			compilerOptions: { 
				css: 'injected',
				// Enable Svelte 4 component API compatibility for existing components
				compatibility: {
					componentApi: 4
				}
			},
		}),
		cssRenamePlugin, // 添加 CSS 重命名插件
	],
	outfile: prod ? 'main.js' : path.join(pluginDir, 'main.js'),
};

// 强制 CSS 提取为单独文件
buildOptions.loader = buildOptions.loader || {};
buildOptions.loader['.css'] = 'css';

if (prod) {
	esbuild
		.build(buildOptions)
		.then(onBuildComplete)
		.catch(() => process.exit(1));
} else {
	const context = await esbuild.context(buildOptions);
	await context.watch();
}
